### ISSUE TITLE
SSL problems with HttpClient in combination with Parse >= 1.9.3

### ISSUE THREAD

**Issue by tehmaestro** [ParsePlatform/Parse-SDK-Android#156]
Hi, I think there is a problem with version >= 1.9.3. I'm creating a `httpClient` to make a request to my own server, which uses `https`. Whenever I try to make a request, I get this:
```
java.lang.NullPointerException
            at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:382)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:173)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:653)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:627)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:616)va:232)
```

It works perfectly when using Parse 1.9.2 . This issue got me searching solutions for days, maybe someone will find this useful. 

My request code has nothing to do with Parse, I just do a regular POST to my server, which happens to use SSL, and I get this error stack, because I was using Parse 1.10.2 . Whoever needs this fixed now, downgrade to 1.9.2

**Comment by wangmengyan95** [comment]
Hi @tehmaestro, right now we do not support connect to arbitrary servers. It seems you still use Apache HttpClient, so for Parse, there is no significant change from 1.9.2 to 1.9.3 for ParseApacheHttpClient, maybe you can try to use ParseOKHttpClient(import okhttp to your app) and ParseURLConnectionClient(make sure your app run on android version >= 4.4) to see whether you still have this problem.
