### ISSUE TITLE
Crash: ParseRequest

### ISSUE THREAD

**Issue by phileo** [ParsePlatform/Parse-SDK-Android#198]
`com.parse.ParseRequest$ParseRequestException: Can't find Installation objects
       at com.parse.ParseRequest.newPermanentException(ParseRequest.java:363)
       at com.parse.ParseRESTCommand.onResponse(ParseRESTCommand.java:192)
       at com.parse.ParseRequest$3.then(ParseRequest.java:229)
       at com.parse.ParseRequest$3.then(ParseRequest.java:225)
       at bolts.Task$14.run(Task.java:796)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeAfterTask(Task.java:787)
       at bolts.Task.continueWithTask(Task.java:599)
       at bolts.Task.continueWithTask(Task.java:610)
       at bolts.Task$12.then(Task.java:702)
       at bolts.Task$12.then(Task.java:690)
       at bolts.Task$14.run(Task.java:796)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by xor22h** [comment]
Maybe this one is related with #201
