### ISSUE TITLE
Android SDK doesn't warn about invalid API credentials

### ISSUE THREAD

**Issue by wkoszek** [ParsePlatform/Parse-SDK-Android#251]
I made a typo in my Parse.initialize() and I get no warnings about the invalid keys. What's most interesting: Parse SDK still reports crash reports are still being uploaded. Are they uploaded always?

Code fragment:

```
    private void parseBootstrap() {
        try {
            Thread.sleep(3000);
        } catch(InterruptedException ex) {
            Thread.currentThread().interrupt();
        }
        ParseAnalytics.trackAppOpenedInBackground(getIntent());

        Parse.setLogLevel(Parse.LOG_LEVEL_DEBUG);

        for (int i = 0; i < 1; i++) {
            System.out.print("XXX wrinting" + i);
            ParseObject testObject = new ParseObject("TestObject");
            testObject.put("foo", "bar");
            testObject.saveInBackground();
        }

        Map<String, String> dimensions = new HashMap<String, String>();
        // What type of news is this?
        dimensions.put("category", "politics");
        // Is it a weekday or the weekend?
        dimensions.put("dayType", "weekday");
        // Send the dimensions to Parse along with the 'read' event

        ParseAnalytics.trackEventInBackground("read", dimensions);

        boolean doTestCrashReporting = true;

        if (SRCfg.doTestCrashReporting || doTestCrashReporting) {
            System.out.print("Will crash app now");
            throw new RuntimeException("Test Exception!");
        }
    }
```

Report:

```
11-16 03:43:31.473 1231-1298/system_process D/TaskPersister: removeObsoleteFile: deleting file=30_task.xml
11-16 03:43:51.067 9054-9054/? D/AndroidRuntime: CheckJNI is ON
11-16 03:43:51.104 9054-9054/? E/memtrack: Couldn't load memtrack module (No such file or directory)
11-16 03:43:51.104 9054-9054/? E/android.os.Debug: failed to load memtrack module: -2
11-16 03:43:51.138 9054-9054/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
11-16 03:43:51.142 1231-1412/system_process I/ActivityManager: Force stopping com.barvoy.sensorama appid=10057 user=0: from pid 9054
11-16 03:43:51.142 1231-1412/system_process I/ActivityManager: Killing 8462:com.barvoy.sensorama/u0a57 (adj 11): stop com.barvoy.sensorama
11-16 03:43:51.170 1231-1245/system_process W/ActivityManager: Spurious death for ProcessRecord{2bf9586a 8462:com.barvoy.sensorama/u0a57}, curProc for 8462: null
11-16 03:43:51.171 9054-9054/? D/AndroidRuntime: Shutting down VM
11-16 03:43:51.186 9054-9057/? I/art: Debugger is no longer active
11-16 03:43:51.195 1231-1706/system_process W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@6ff82d1 attribute=null, token = android.os.BinderProxy@13edc171
11-16 03:43:51.559 9075-9075/? D/AndroidRuntime: CheckJNI is ON
11-16 03:43:51.617 9075-9075/? E/memtrack: Couldn't load memtrack module (No such file or directory)
11-16 03:43:51.617 9075-9075/? E/android.os.Debug: failed to load memtrack module: -2
11-16 03:43:51.641 9075-9075/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
11-16 03:43:51.651 1231-1287/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.barvoy.sensorama/.MainActivity} from uid 0 on display 0
11-16 03:43:51.675 9075-9075/? D/AndroidRuntime: Shutting down VM
11-16 03:43:51.675 9075-9077/? I/art: Debugger is no longer active
11-16 03:43:51.693 1231-1412/system_process I/ActivityManager: Start proc com.barvoy.sensorama for activity com.barvoy.sensorama/.MainActivity: pid=9085 uid=10057 gids={50057, 9997, 1028, 1015, 3003} abi=x86
11-16 03:43:51.697 9085-9085/? I/art: Not late-enabling -Xcheck:jni (already on)
11-16 03:43:51.892 9085-9085/com.barvoy.sensorama D/CrashReporting: Crash reporting is enabled for com.barvoy.sensorama, initializing...
11-16 03:43:51.900 9085-9085/com.barvoy.sensorama D/CrashReporting: Looking for error files in /data/data/com.barvoy.sensorama/files/com.parse/cr/reports
11-16 03:43:51.901 9085-9085/com.barvoy.sensorama D/CrashReporting: Looking for error files in /data/data/com.barvoy.sensorama/files/com.parse/cr/minidumps
11-16 03:43:51.980 9085-9085/com.barvoy.sensorama I/System.out: Storage detected
11-16 03:43:51.982 9085-9085/com.barvoy.sensorama I/System.out: Free storage: 196
11-16 03:43:51.983 9085-9085/com.barvoy.sensorama I/System.out: SD not available
11-16 03:43:55.026 9085-9085/com.barvoy.sensorama D/AndroidRuntime: Shutting down VM
11-16 03:43:55.026 9085-9085/com.barvoy.sensorama E/CrashReporting: ParseCrashReporting caught a RuntimeException exception for com.barvoy.sensorama. Building report.
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting: Handling exception for crash
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.barvoy.sensorama/com.barvoy.sensorama.MainActivity}: java.lang.RuntimeException: Test Exception!
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread.access$800(ActivityThread.java:144)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.os.Looper.loop(Looper.java:135)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread.main(ActivityThread.java:5221)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at java.lang.reflect.Method.invoke(Native Method)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at java.lang.reflect.Method.invoke(Method.java:372)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:  Caused by: java.lang.RuntimeException: Test Exception!
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at com.barvoy.sensorama.MainActivity.parseBootstrap(MainActivity.java:286)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at com.barvoy.sensorama.MainActivity.onCreate(MainActivity.java:58)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.Activity.performCreate(Activity.java:5937)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread.access$800(ActivityThread.java:144) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.os.Looper.loop(Looper.java:135) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at android.app.ActivityThread.main(ActivityThread.java:5221) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at java.lang.reflect.Method.invoke(Native Method) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama E/CrashReporting:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
11-16 03:43:55.027 9085-9085/com.barvoy.sensorama D/CrashReporting: Generating report file for crash
11-16 03:43:55.072 9085-9085/com.barvoy.sensorama D/CrashReporting: Retrieving logcat output...
11-16 03:43:55.088 9085-9085/com.barvoy.sensorama D/CrashReporting: Retrieving logcat output...
11-16 03:43:55.098 9085-9085/com.barvoy.sensorama D/CrashReporting: Retrieving logcat output...
11-16 03:43:55.153 9085-9085/com.barvoy.sensorama V/CrashReporting: About to start ReportSenderWorker from #handleException
11-16 03:43:55.155 9085-9170/com.barvoy.sensorama D/CrashReporting: #checkAndSendReports - start
11-16 03:43:55.155 9085-9170/com.barvoy.sensorama D/CrashReporting: Looking for error files in /data/data/com.barvoy.sensorama/files/com.parse/cr/reports
11-16 03:43:55.156 9085-9170/com.barvoy.sensorama D/CrashReporting: Loading file 1447674235027-RuntimeException-1.stacktrace
11-16 03:43:55.160 9085-9170/com.barvoy.sensorama I/CrashReporting: Sending file 1447674235027-RuntimeException-1.stacktrace
11-16 03:43:55.160 9085-9170/com.barvoy.sensorama D/CrashReporting: Sending crash report to Parse...
11-16 03:43:55.162 9085-9170/com.barvoy.sensorama D/CrashReporting: #checkAndSendReports - finish
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime: FATAL EXCEPTION: main
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime: Process: com.barvoy.sensorama, PID: 9085
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.barvoy.sensorama/com.barvoy.sensorama.MainActivity}: java.lang.RuntimeException: Test Exception!
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:144)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5221)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:  Caused by: java.lang.RuntimeException: Test Exception!
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at com.barvoy.sensorama.MainActivity.parseBootstrap(MainActivity.java:286)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at com.barvoy.sensorama.MainActivity.onCreate(MainActivity.java:58)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5937)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:144) 
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5221) 
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
11-16 03:43:55.263 9085-9085/com.barvoy.sensorama E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
11-16 03:43:55.268 1231-1707/system_process W/ActivityManager:   Force finishing activity com.barvoy.sensorama/.MainActivity
11-16 03:43:55.613 1231-1707/system_process I/WindowManager: Screenshot max retries 4 of Token{1dca21a4 ActivityRecord{119c7837 u0 com.barvoy.sensorama/.MainActivity t31 f}} appWin=Window{35c88ac2 u0 Starting com.barvoy.sensorama} drawState=4
11-16 03:43:55.613 1231-1707/system_process E/ActivityManager: Invalid thumbnail dimensions: 576x576
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue: Failed to run command.
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue: com.parse.ParseRequest$ParseRequestException: unauthorized
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest.newPermanentException(ParseRequest.java:301)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:288)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest$3.then(ParseRequest.java:151)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest$3.then(ParseRequest.java:147)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$15.run(Task.java:825)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.completeAfterTask(Task.java:816)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.continueWithTask(Task.java:628)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.continueWithTask(Task.java:639)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$13.then(Task.java:731)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$13.then(Task.java:719)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$15.run(Task.java:825)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-16 03:43:55.691 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.lang.Thread.run(Thread.java:818)
11-16 03:43:55.709 1231-1276/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
11-16 03:43:55.730 1231-1276/system_process W/EGL_emulation: eglSurfaceAttrib not implemented
11-16 03:43:55.730 1231-1276/system_process W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa5e55720, error=EGL_SUCCESS
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue: Failed to run command.
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue: com.parse.ParseRequest$ParseRequestException: unauthorized
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest.newPermanentException(ParseRequest.java:301)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:288)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest$3.then(ParseRequest.java:151)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest$3.then(ParseRequest.java:147)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$15.run(Task.java:825)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.completeAfterTask(Task.java:816)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.continueWithTask(Task.java:628)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.continueWithTask(Task.java:639)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$13.then(Task.java:731)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$13.then(Task.java:719)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$15.run(Task.java:825)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-16 03:43:55.921 9085-9158/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.lang.Thread.run(Thread.java:818)
11-16 03:43:56.133 1231-1249/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{119c7837 u0 com.barvoy.sensorama/.MainActivity t31 f}
11-16 03:43:56.229 1476-1636/com.android.launcher I/OpenGLRenderer: Initialized EGL, version 1.4
11-16 03:43:56.245 1476-1636/com.android.launcher W/EGL_emulation: eglSurfaceAttrib not implemented
11-16 03:43:56.245 1476-1636/com.android.launcher W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa6c1b200, error=EGL_SUCCESS
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue: Failed to run command.
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue: com.parse.ParseRequest$ParseRequestException: unauthorized
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest.newPermanentException(ParseRequest.java:301)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:288)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest$3.then(ParseRequest.java:151)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest$3.then(ParseRequest.java:147)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$15.run(Task.java:825)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.completeAfterTask(Task.java:816)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.continueWithTask(Task.java:628)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.continueWithTask(Task.java:639)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$13.then(Task.java:731)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$13.then(Task.java:719)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$15.run(Task.java:825)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-16 03:43:56.254 9085-9160/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.lang.Thread.run(Thread.java:818)
11-16 03:43:56.654 1476-1492/com.android.launcher I/art: WaitForGcToComplete blocked for 11.641ms for cause Background
11-16 03:43:56.775 1476-1492/com.android.launcher I/art: Background partial concurrent mark sweep GC freed 22869(1646KB) AllocSpace objects, 36(2MB) LOS objects, 19% free, 16MB/20MB, paused 9.193ms total 114.937ms
11-16 03:44:00.075 1476-1636/com.android.launcher W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
11-16 03:44:06.493 1231-1249/system_process W/ActivityManager: Activity destroy timeout for ActivityRecord{119c7837 u0 com.barvoy.sensorama/.MainActivity t31 f}
11-16 03:44:10.014 1231-1298/system_process D/TaskPersister: removeObsoleteFile: deleting file=31_task.xml
```

now I delete the `setLogLevel` and I get the same except these printouts:

```
11-16 03:51:26.636 14724-14736/com.barvoy.sensorama I/art: Background sticky concurrent mark sweep GC freed 9442(600KB) AllocSpace objects, 0(0B) LOS objects, 21% free, 1579KB/2013KB, paused 234.153ms total 1.301s
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue: Failed to run command.
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue: com.parse.ParseRequest$ParseRequestException: unauthorized
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest.newPermanentException(ParseRequest.java:301)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:288)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest$3.then(ParseRequest.java:151)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at com.parse.ParseRequest$3.then(ParseRequest.java:147)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$15.run(Task.java:825)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.completeAfterTask(Task.java:816)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.continueWithTask(Task.java:628)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task.continueWithTask(Task.java:639)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$13.then(Task.java:731)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$13.then(Task.java:719)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at bolts.Task$15.run(Task.java:825)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-16 03:51:26.965 14724-14751/com.barvoy.sensorama D/ParsePinningEventuallyQueue:     at java.lang.Thread.run(Thread.java:818)
```

Summary: looks like a presence of increased logging causes the first "event" that API credentials aren't OK. I'd expect this warning to be printed out much earlier.

**Comment by grantland** [comment]
Invalid Parse credentials will generally be surfaced when calling `ParseObject#save()`, `ParseAnalytics#trackEventInBackground(event, dimensions)`, etc.

Crash reports might still be uploaded, but they won't be able to be accessed from your account.
