### ISSUE TITLE
com.parse.ParseRequest$ParseRequestException: missing user password

### ISSUE THREAD

**Issue by vfede** [ParsePlatform/Parse-SDK-Android#300]
http://crashes.to/s/3ccfa1fa59d

using:
com.parse:parse-android:1.11.0
com.parse.bolts:bolts-android:1.3.0
ParseFacebookUtilsV4-1.10.3.jar
com.squareup.okhttp:okhttp:2.6.0
com.squareup.okhttp:okhttp-urlconnection:2.6.0

I use lazy users,  I'm not using before/afterSave on my users.
The order of my initialization is this:

```java
public class MyApplication extends Application {

	@Override
	public void onCreate() {
		super.onCreate();
 
		ParseObject.registerSubclass(MyUser.class);
		Parse.initialize(...);
		ParseFacebookUtils.initialize(appContext, REQUESTCODE_FACEBOOK);
		FacebookSdk.sdkInitialize(appContext);
		MyUser.enableAutomaticUser();
		MyUser user = MyUser.getCurrentUser();
		String userId = user.getUserId(); //here it does the first user save
		...
```

this is part of MyUser class
```java

@ParseClassName("_User")
public class MyUser extends ParseUser {

//more methods

public synchronized String getUserId() {
		if (MyUser.getCurrentUser().getObjectId() == null)
		try {
			MyUser.getCurrentUser().save();
			} catch(ParseException e) {
				// this is where the exception got caught
				Crashlytics.getInstance().core.logException(e);
				//fallback to temporary id, logic not shown
				return temporaryId;
			}

		return getObjectId();
	}

public static MyUser getCurrentUser() {
		return (MyUser) ParseUser.getCurrentUser();
	}
}
```

is there any problem in the way I save for the first time MyUser object? or the way I cast ParseUser to MyUser?

seems like the "enableAutomaticUser" did not set the password, or maybe is something else hiding behind this error?
I do it syncronously and if any problem occurs I fallback to a temporary id because I need an id on app startup.

**Comment by grantland** [comment]
Could you provide us with a small sample project that reproduces this issue? I'm not entirely aware of the entire context of what's happening.

Also, it seems like you're doing a synchronous network call with `#save()` on the main thread, which is something you should never do.

**Comment by vfede** [comment]
ok I managed to change the code to avoid the sync save, but with async save I got the same error when the init() method is called in very fast sequence.
the init() method should be called when the user still does not have an id, so the first save() will assign the id.
the error is raised after the userId is correctly assigned the first time.

```java
public static void init() {
		MyUser user = MyUser.getCurrentUser();

		Log.d("parse issue", "Start User Save at " + SystemClock.elapsedRealtime());
		Log.d("parse issue", "userId: " + user.getUserId());

		user.saveInBackground(new SaveCallback() {
			@Override
			public void done(ParseException e) {

				MyUser user = MyUser.getCurrentUser();
				String userId = user.getUserId();

				if (e != null) {
					Log.d("parse issue", "error: " + e.getMessage());
					Log.d("parse issue", "userId on error: " + userId);}
				else
					Log.d("parse issue", "userId on save: " + userId);

				if (e != null) 
					EventLogger.logUserSaveError(e.getMessage());
				else if (Utils.isNullOrEmpty(userId))
					EventLogger.logUserSaveError("User is null or empty after save: >" + user + "<");
				else {
					// user creation successfull
					setUserOnCrashlytics(user);
					MyUser.subscribeToPush(userId);
				}
			}
		});
	}
```

these logs like this:
```
D/parse issue: Start User Save at 924172910
D/parse issue: userId: null
D/parse issue: Start User Save at 924172978
D/parse issue: userId: null
D/parse issue: Start User Save at 924172989
D/parse issue: userId: null
D/parse issue: Done User Save at 924173967
D/parse issue: userId on save: Z4didGbXS9
D/parse issue: Done User Save at 924174302
D/parse issue: error: missing user password
D/parse issue: userId on error: Z4didGbXS9
D/parse issue: Done User Save at 924174524
D/parse issue: error: missing user password
D/parse issue: userId on error: Z4didGbXS9
```
it is clear that my code calls init() too much times and too fast, but why that error is raised? is it right? thanks

**Comment by grantland** [comment]
It's hard to tell without a complete understanding of your code, but it could be that you're modifying the current user at the same time as these saves. 

Is there any reason this needs to be called so many times in parallel?

Do you have the stack trace of the errors?

Could you have the same log output, but with `user`'s hashcode?

Is your original error resolved?

**Comment by vfede** [comment]
the error that's the topic of the thread disappeared when I dropped the sync save, but this new event appeared. I can fix this with a proper condition inside the saveInBackground callback, that checks null and userId.

As your request, this is the new log (code updated too):

```
D/parse issue: Start User Save at 161734651
D/parse issue: userId: null
D/parse issue: userHash: 1108973056
D/parse issue: Start User Save at 161734725
D/parse issue: userId: null
D/parse issue: userHash: 1108973056
D/parse issue: Start User Save at 161734728
D/parse issue: userId: null
D/parse issue: userHash: 1108973056
D/parse issue: userId on save: RpOC7XNTut
D/parse issue: userHash on save: 1108973056
E/parse issue: error: missing user password
W/System.err: com.parse.ParseRequest$ParseRequestException: missing user password
W/System.err:     at com.parse.ParseRequest.newPermanentException(ParseRequest.java:269)
W/System.err:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:288)
W/System.err:     at com.parse.ParseRESTUserCommand.onResponseAsync(ParseRESTUserCommand.java:126)
W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:136)
W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:132)
W/System.err:     at bolts.Task$15.run(Task.java:839)
W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
W/System.err:     at bolts.Task.completeAfterTask(Task.java:830)
W/System.err:     at bolts.Task.continueWithTask(Task.java:642)
W/System.err:     at bolts.Task.continueWithTask(Task.java:653)
W/System.err:     at bolts.Task$13.then(Task.java:745)
W/System.err:     at bolts.Task$13.then(Task.java:733)
W/System.err:     at bolts.Task$15.run(Task.java:839)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
D/parse issue: userId on error: RpOC7XNTut
D/parse issue: userHash on error: 1108973056
E/parse issue: error: missing user password
W/System.err: com.parse.ParseRequest$ParseRequestException: missing user password
W/System.err:     at com.parse.ParseRequest.newPermanentException(ParseRequest.java:269)
W/System.err:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:288)
W/System.err:     at com.parse.ParseRESTUserCommand.onResponseAsync(ParseRESTUserCommand.java:126)
W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:136)
W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:132)
W/System.err:     at bolts.Task$15.run(Task.java:839)
W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
W/System.err:     at bolts.Task.completeAfterTask(Task.java:830)
W/System.err:     at bolts.Task.continueWithTask(Task.java:642)
W/System.err:     at bolts.Task.continueWithTask(Task.java:653)
W/System.err:     at bolts.Task$13.then(Task.java:745)
W/System.err:     at bolts.Task$13.then(Task.java:733)
W/System.err:     at bolts.Task$15.run(Task.java:839)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
D/parse issue: userId on error: RpOC7XNTut
D/parse issue: userHash on error: 1108973056
```

really thanks @grantland to addressing this issue.

**Comment by grantland** [comment]
Would you be able to provide a small project that repros this issue?

**Comment by vfede** [comment]
I finally managed to set up a project that reproduce the issue.
@grantland you can find it here. hope this finally helps.

https://github.com/vfede/MyApplication
