### ISSUE TITLE
I'm getting allot of crashes from my users -IllegalStateException: Attempted to find non-existent

### ISSUE THREAD

**Issue by roeef** [ParsePlatform/Parse-SDK-Android#313]
Hello,
Please advice -
I'm using Parse on Android and seeing repeated crashes from users of my app -
Using parse SDK 1.10.0 - 
The error started since upgrading 1.10.0 -
It didn't happen in 1.8.2

Here's a stack trace -
"
java.lang.IllegalStateException: Attempted to find non-existent uuid 3b4bf412-035f-474e-8c96-7ea97f75aa13
	at com.parse.OfflineStore$3.then(OfflineStore.java:269)
	at com.parse.OfflineStore$3.then(OfflineStore.java:262)
	at bolts.Task$14.run(Task.java:784)
	at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
	at bolts.Task.completeImmediately(Task.java:775)
	at bolts.Task.continueWith(Task.java:574)
	at bolts.Task.continueWith(Task.java:585)
	at bolts.Task$12.then(Task.java:679)
	at bolts.Task$12.then(Task.java:667)
	at bolts.Task$15.run(Task.java:825)
	at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
	at bolts.Task.completeAfterTask(Task.java:816)
	at bolts.Task.access$200(Task.java:32)
	at bolts.Task$11.then(Task.java:621)
	at bolts.Task$11.then(Task.java:618)
	at bolts.Task.runContinuations(Task.java:861)
	at bolts.Task.access$600(Task.java:32)
	at bolts.Task$TaskCompletionSource.trySetResult(Task.java:916)
	at bolts.Task$TaskCompletionSource.setResult(Task.java:950)
	at bolts.Task$15$1.then(Task.java:842)
	at bolts.Task$15$1.then(Task.java:829)
	at bolts.Task$14.run(Task.java:784)
	at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
	at bolts.Task.completeImmediately(Task.java:775)
	at bolts.Task.continueWith(Task.java:574)
	at bolts.Task.continueWith(Task.java:585)
	at bolts.Task$15.run(Task.java:829)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
"

**Comment by roeef** [comment]
The error started since upgrading 1.10.0 -
It didn't happen in 1.8.2

**Comment by wangmengyan95** [comment]
Hi @roeef, the exception means the SDK try to query some none existed object from local datastore. We want to know do you use local datastore in 1.8.2 and how do you use that. Is it possible for you to provide us with a sample project which can repo this issue? Thanks.

**Comment by roeef** [comment]
Hi @wangmengyan95 ,

Were using pretty often -  
It didn't happen or reproduce in the lab - 
Were seeing it in analytic reports since we upgraded the to SDK 1.10.3

Were seeing the error thrown in about 400 users out of about 100,000 active users.
So it's not in the main flow of usage.

If you have a version that can give me extra info in the stack when the error is thrown this would be useful to assist us to reproduce.

**Comment by wangmengyan95** [comment]
Hi @roeef, we have some internal log which you can check in Android console. You can enable them by using `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE)`. However, I doubt it is very useful for your case since this issue is highly related to the usage of local datastore, not how local datastore works. If you can repo this bug, feel free to give us a sample project. We are happy to help you find the issue.

**Comment by roeef** [comment]
Hi @wangmengyan95,
Is there a way to get a more detailed data on the thrown stack trace that would indicate which of my local data-store usages could have caused it?
class or query data ? 
what does the UUID that apears in the stack indicates?

The logging won't be useful at the moment since it doesn't happen in our labs at all - only on real users out there.

**Comment by wangmengyan95** [comment]
Hi @roeef, UUID is similar to objectId of a ParseObject. It is the identifier of a ParseObject in local datastore. Right now it is hard to get detailed data only on stacktrace. The best way to debug is still get access to the database. However, it is not possible in your case.

**Comment by roeef** [comment]
It seems it is happening only\mostly on Motorola device.....

**Comment by avalenzuelac** [comment]
Hello, is there still no solution for this problem? Regards

**Comment by ZeekHuge** [comment]
I noticed that, for the emulator, If I reinstall the debug-app, the `ParseInstallation` object is lost. I tried looking into the `ParseOfflineStore` file for the app, and the `_Pin` object for the `ParseInstallation` object exists, and all the right data in the `Dependecies` table, but the actuall `ParseInstallation` object (that is `_Installation` object ) was missing. It was lost.

**Comment by ZeekHuge** [comment]
I am not sure If I should ping, but since the issue is a closed one and there was no reply after 2 days after I reported a way to reproduce the error. I would try to do it once.
So ... 
@wangmengyan95 - ^^

**Comment by flovilmart** [comment]
Can you please open a new issue? We usually don’t follow up on closed issues from 2 years ago :) @rogerhu
