### ISSUE TITLE
error 100 i/o failure

### ISSUE THREAD

**Issue by yfsx** [ParsePlatform/Parse-SDK-Android#325]
error #188 happens to me, but it really strange :(

i have 5 phone to be tested (xiaomi 4i, asus zenfone 5, samsung galaxy tab, samsung s4, and sony c5) in same network with same apps. error 100 i/o failure returned on samsung galaxy tab and sony c5, meanwhile the three (xiaomi 4i, zenfone 5 and s4) working perfectly. what's going on with parse?

        final ParseQuery<ParseObject> query = ParseQuery.getQuery("Workout");
        query.addDescendingOrder("priority");
        query.whereEqualTo("workoutType", someInt);
        query.whereEqualTo("public", true);
        query.setLimit(limit);
        query.setSkip((page - 1) * currentPagingModel.pageSize);

        query.findInBackground(new FindCallback<ParseObject>() {
            @Override
            public void done(List<ParseObject> objects, ParseException e) {
                if(e == null) {
                    if (!objects.isEmpty()) {
                       *blablabla*
                    }
                }else{
                }

same error happened when i call some cloud function
thanks

EDIT: 
this is from sony c5 debug
![screen shot 2015-12-30 at 9 44 43 am](https://cloud.githubusercontent.com/assets/10009357/12045654/1a14b240-aeda-11e5-9313-f432c258635a.png)

**Comment by grantland** [comment]
Could you post an actual stack trace as opposed to a screenshot?

**Comment by yfsx** [comment]
like this one? 

failure: com.parse.ParseRequest$ParseRequestException: i/o failure
                                                                         at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:289)
                                                                         at com.parse.ParseRequest$2.then(ParseRequest.java:144)
                                                                         at com.parse.ParseRequest$2.then(ParseRequest.java:138)
                                                                         at bolts.Task$15.run(Task.java:839)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                         at java.lang.Thread.run(Thread.java:841)
                                                                      Caused by: java.io.IOException: unknown format (magic number 227b)
                                                                         at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:101)
                                                                         at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:81)
                                                                         at com.parse.ParseDecompressInterceptor.intercept(ParseDecompressInterceptor.java:40)
                                                                         at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
                                                                         at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
                                                                         at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
                                                                         at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
                                                                         at com.parse.ParseRequest$3.then(ParseRequest.java:135)
                                                                         at com.parse.ParseRequest$3.then(ParseRequest.java:132)
                                                                         at bolts.Task$15.run(Task.java:839)
                                                                         at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                                                         at bolts.Task.completeAfterTask(Task.java:830)
                                                                         at bolts.Task.continueWithTask(Task.java:642)
                                                                         at bolts.Task.continueWithTask(Task.java:653)
                                                                         at bolts.Task$13.then(Task.java:745)
                                                                         at bolts.Task$13.then(Task.java:733)
                                                                         at bolts.Task$15.run(Task.java:839) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                                         at java.lang.Thread.run(Thread.java:841)

**Comment by grantland** [comment]
It looks like something is wrong with the networking on this device. Could you post the network request and responses using [ParseInterceptors](https://github.com/ParsePlatform/ParseInterceptors-Android) or something similar?

**Comment by yfsx** [comment]
thats really strange, i just add parse interceptors and all device working perfectly. 5 days i working on it and suddenly disappeared! i will investigate it, and thanks!

**Comment by grantland** [comment]
`ParseLogInterceptor` is already built in: https://github.com/ParsePlatform/ParseInterceptors-Android/wiki/ParseLogInterceptor

**Comment by yfsx** [comment]
it seems there isn't any ParseLogInterceptor, i just add it to save time.

thanks!!!
