### ISSUE TITLE
Parse SDK is crashing during sign up process with following stack trace. 

### ISSUE THREAD

**Issue by kodeshpa** [ParsePlatform/Parse-SDK-Android#344]
If i set ACL before sign up then during sign up application is crashing with following error.

                                                                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.lang.IllegalStateException: unable to encode an association with an unsaved ParseObject
                                                                         at com.parse.PointerEncoder.encodeRelatedObject(PointerEncoder.java:31)
                                                                         at com.parse.ParseEncoder.encode(ParseEncoder.java:42)
                                                                         at com.parse.ParseACL.toJSONObject(ParseACL.java:150)
                                                                         at com.parse.ParseEncoder.encode(ParseEncoder.java:82)
                                                                         at com.parse.ParseSetOperation.encode(ParseSetOperation.java:27)
                                                                         at com.parse.ParseEncoder.encode(ParseEncoder.java:129)
                                                                         at com.parse.ParseObjectCoder.encode(ParseObjectCoder.java:60)
                                                                         at com.parse.NetworkUserController.signUpAsync(NetworkUserController.java:41)
                                                                         at com.parse.ParseUser$8.then(ParseUser.java:675)
                                                                         at com.parse.ParseUser$8.then(ParseUser.java:672)
                                                                         at bolts.Task$15.run(Task.java:839)
                                                                         at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                                                         at bolts.Task.completeAfterTask(Task.java:830)
                                                                         at bolts.Task.continueWithTask(Task.java:642)
                                                                         at bolts.Task.continueWithTask(Task.java:653)
                                                                         at bolts.Task$13.then(Task.java:745)
                                                                         at bolts.Task$13.then(Task.java:733)
                                                                         at bolts.Task$15.run(Task.java:839)
                                                                         at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                                                         at bolts.Task.completeAfterTask(Task.java:830)
                                                                         at bolts.Task.continueWithTask(Task.java:642)
                                                                         at bolts.Task.continueWithTask(Task.java:617)
                                                                         at bolts.Task.onSuccessTask(Task.java:733)
                                                                         at bolts.Task.onSuccessTask(Task.java:723)
                                                                         at bolts.Task.onSuccessTask(Task.java:757)
                                                                         at com.parse.ParseUser.signUpAsync(ParseUser.java:672)
                                                                         at com.parse.ParseUser.resolveLazinessAsync(ParseUser.java:1359)
                                                                         at com.parse.ParseUser.saveAsync(ParseUser.java:481)
                                                                         at com.parse.ParseUser.signUpAsync(ParseUser.java:641)
                                                                         at com.parse.ParseUser$6.then(ParseUser.java:580)
                                                                         at com.parse.ParseUser$6.then(ParseUser.java:577)
                                                                         at com.parse.TaskQueue.enqueue(TaskQueue.java:69)
                                                                         at com.parse.ParseUser.signUpInBackground(ParseUser.java:577)
                                                                         at com.parse.ParseUser.signUp(ParseUser.java:713)
                                                                         at com.pingbaba.business.LoginActivity$UserLoginTask.doInBackground(LoginActivity.java:240)
                                                                         at com.pingbaba.business.LoginActivity$UserLoginTask.doInBackground(LoginActivity.java:214)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                         at java.lang.Thread.run(Thread.java:818)

**Comment by alexblack** [comment]
I've seen this exception when I attempt to reference one ParseObject on another, when the first has not been saved.

For example, if the ParseUser object has not been saved, and you try to reference it on another object, and save that one, then I get this exception. 

You can determine if a ParseObject has been saved by checking whether or not its objectId is null.
