### ISSUE TITLE
Bad JSON Response

### ISSUE THREAD

**Issue by anibalbastias** [ParsePlatform/Parse-SDK-Android#347]
Hi! While I run my Parse Android app, it fails to create a row in the Installation class and responds with a "bad json response". Please fix it! Thanks

`
 com.parse.ParseRequest$ParseRequestException: bad json response
        at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:289)
	at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:308)
	at com.parse.ParseRequest$3.then(ParseRequest.java:136)
	at com.parse.ParseRequest$3.then(ParseRequest.java:132)
	at bolts.Task$15.run(Task.java:917)
	at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
	at bolts.Task.completeAfterTask(Task.java:908)
	at bolts.Task.continueWithTask(Task.java:715)
	at bolts.Task.continueWithTask(Task.java:726)
`

**Comment by anibalbastias** [comment]
Thanks! I fix it changing in builid.gradle:

`
compile 'com.parse:parse-android:1.+'
`

to

`
compile 'com.parse:parse-android:1.12.0'
`

Thanks ! Best!

**Comment by guarani** [comment]
This could be due to the lack of a trailing slash in the server URL, see:
https://github.com/ParsePlatform/parse-server/issues/183#issuecomment-178893298
