### ISSUE TITLE
Issue after migrating to Parse Server With latest SDK 1.13.0

### ISSUE THREAD

**Issue by kumarkeviv** [ParsePlatform/Parse-SDK-Android#394]
Hi All

I had migrated one of my app db to Mongo Lab and hosted the Parse Server on Azure with standard procedure and parse server is running fine there. Then I updated my Parse SDK to latest 1.13.0 as instructed and redirected my app to new hosted Parse Server... But when i launch my app any Parse query is not working.

Here is logcat:

FATAL EXCEPTION: main Process: com.phoenixapplabs.hrinterview, PID: 23555
java.lang.NoClassDefFoundError: bolts.TaskCompletionSource
at com.parse.ParseQuery$3$1.then(ParseQuery.java:1222)
at com.parse.ParseQuery$3$1.then(ParseQuery.java:1218)
at bolts.Task$14.run(Task.java:796)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeAfterTask(Task.java:787)
at bolts.Task.continueWithTask(Task.java:599)
at bolts.Task.continueWithTask(Task.java:610)
at bolts.Task$12.then(Task.java:702)
at bolts.Task$12.then(Task.java:690)
at bolts.Task$14.run(Task.java:796)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeAfterTask(Task.java:787)
at bolts.Task.continueWithTask(Task.java:599)
at bolts.Task.continueWithTask(Task.java:574)
at bolts.Task.onSuccessTask(Task.java:690)
at bolts.Task.onSuccessTask(Task.java:680)
at bolts.Task.onSuccessTask(Task.java:714)
at com.parse.ParseQuery$3.call(ParseQuery.java:1218)
at com.parse.ParseQuery$3.call(ParseQuery.java:1215)
at com.parse.ParseQuery.doWithRunningCheck(ParseQuery.java:1154)
at com.parse.ParseQuery.findAsync(ParseQuery.java:1215)
at com.parse.ParseQuery.findInBackground(ParseQuery.java:1202)
at com.phoenixapplabs.hrinterview.Login_Multiple.parse_registration(Login_Multiple.java:717)
at com.phoenixapplabs.hrinterview.Login_Multiple.onResult(Login_Multiple.java:695)
at com.phoenixapplabs.hrinterview.Login_Multiple.onResult(Login_Multiple.java:71)
at com.google.android.gms.common.api.AbstractPendingResult$CallbackHandler.deliverResultCallback(Unknown Source)
at com.google.android.gms.common.api.AbstractPendingResult$CallbackHandler.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:149)
at android.app.ActivityThread.main(ActivityThread.java:5257)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
at dalvik.system.NativeStart.main(Native Method)

I had successfully added the redirection to azure hosted parse server, here is the code:

 Parse.initialize(new Parse.Configuration.Builder(getBaseContext())
                        .applicationId("JhORpA6c8WfonSimb3FDGcrN0cBSlgwuru6o5dHn")
                        .clientKey("fXQZ8m5kLv1mVj1sa5p05afPy5vW4nvS29DULSgC")
                        .server("http://hr-interview.azurewebsites.net")
                        .build()
        );
 
I think the issue is the with the SDK, I don't know how to proceed plz help.

**Comment by grantland** [comment]
It looks like you're somehow missing the bolts dependency. Can you post your `build.gradle`, any files you have in `libs` and your proguard configuration?

**Comment by kumarkeviv** [comment]
Hi Grantland

Please find my dependencies below:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    //Play Service
    compile 'com.google.android.gms:play-services:7.5.0'
    //Analytics
    compile 'com.google.android.gms:play-services-analytics:7.3.0'
    //FB SDK
    compile 'com.facebook.android:facebook-android-sdk:4.1.0'
    //Material Progress Bar
    compile 'com.github.rahatarmanahmed:circularprogressview:2.4.0'
    //Rainbow Button and Button Effect
    compile 'com.github.dmytrodanylyk.android-process-button:library:1.0.4'
    compile 'info.hoang8f:fbutton:1.0.5'
    //Parse SDK
    //compile 'com.parse.bolts:bolts-android:1.+'
    compile fileTree(dir: 'libs', include: 'Parse-*.jar')
    //Material Dialog
    compile('com.github.afollestad.material-dialogs:core:0.8.5.2@aar') {
        transitive = true
    }
    //Material Ripple
    compile 'com.balysv:material-ripple:1.0.2'
    compile 'com.github.traex.rippleeffect:library:1.3'
    //Drawer Navigation
    compile 'br.com.liveo:navigationdrawer-material:2.3.3'
    //Floating Button List View
    compile 'com.melnykov:floatingactionbutton:1.3.0'
    //Multiple Floating Button
    compile 'com.github.clans:fab:1.6.2'
    //Other Donut Graph Chart
    compile 'com.github.blackfizz:eazegraph:1.2.2@aar'
    compile 'com.nineoldandroids:library:2.4.0'
    //Round Profile Pic
    compile 'de.hdodenhof:circleimageview:2.0.0'
    //IOS like Switch
    compile 'com.kyleduo.switchbutton:library:1.2.9'
    //Youtube API's
    compile files('libs/YouTubeAndroidPlayerApi.jar')
    //Loading More Dialog
    compile 'com.victor:lib:1.0.1'
    //Sweet Dialog
    compile 'cn.pedant.sweetalert:library:1.3'
    //Multidex
    compile 'com.android.support:multidex:1.0.0'
    //Refresh
    compile 'com.baoyz.pullrefreshlayout:library:1.2.0'
}


I have commented the 
 //compile 'com.parse.bolts:bolts-android:1.+' 
because every-time i un-comment this, I get this error

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: bolts/AggregateException.class.


Thanks for coming forward for help.

**Comment by grantland** [comment]
>```
compile fileTree(dir: 'libs', include: 'Parse-*.jar')
//compile 'com.parse:parse-android:1.+'
```

We do not recommend using `.jar`s when possible and recommend using Maven dependencies instead. Remove the first line, delete the file `/libs/Parse-x.x.x.jar`, and uncomment the second line.

In addition, we recommend using hard version numbering on dependencies, in this case it will be 1.13.0.

> **I have commented the 
//compile 'com.parse.bolts:bolts-android:1.+' 
because every-time i un-comment this, I get this error**

This is probably due to the fact that  `com.facebook.android:facebook-android-sdk:4.1.0` depends on an incompatible version of bolts. You'll need to use 4.9 or later.

You also shouldn't need to manually add the `bolts-android` dependency if you're correctly using Maven for Parse.

If you're still having issues, check #213 since I've noticed you're using multidex.

**Comment by kumarkeviv** [comment]
Thanks Grantland

You worked as life saver, this issue was resolved by steps you suggested to follow. Now I am able to query still unable get the response from my parse server hosted on Azure, but that is a different case. You can close this issue now.

Thanks again for such an immediate help.

**Comment by grantland** [comment]
Awesome, glad to hear!
