### ISSUE TITLE
ParseInstallation.getDeviceToken()' on a null object reference with Optimize Proguard

### ISSUE THREAD

**Issue by sakebook** [ParsePlatform/Parse-SDK-Android#415]
With Proguard, MyApplication will crash on launch.

Error is as below.

```
java.lang.RuntimeException: Unable to create application xxx.xxx.xxx.MyApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.parse.ParseInstallation.getDeviceToken()' on a null object reference
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.parse.ParseInstallation.getDeviceToken()' on a null object reference
                                                       at com.parse.GcmRegistrar.registerAsync(GcmRegistrar.java:99)
                                                       at com.parse.Parse.initialize(Parse.java:231)
                                                       at xxx.xxx.xxx.MyApplication.onCreate(MyApplication.java:58)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Setting of Proguard is as below.

 * build.gradle
```
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
```

 * proguard-rules.pro

```
...
# Parse
-dontwarn bolts.**
-dontwarn com.parse.**

# Keep source file names, line numbers, and Parse class/method names for easier debugging
-keepattributes SourceFile,LineNumberTable
-keepnames class com.parse.** { *; }

# Required for Parse
-keepattributes *Annotation*
-keepattributes Signature
-dontwarn android.net.SSLCertificateSocketFactory
-dontwarn android.app.Notification
-dontwarn com.squareup.**
-dontwarn okio.**
-keep class com.parse.** { *; }
-keep class bolts.** { *; }
-keepnames class bolts.** { *; }
-dontwarn com.squareup.**
...
```

**Comment by sakebook** [comment]
I used sdk version is 1.11.0.
But I get the same error even 1.13.0.

**Comment by sakebook** [comment]
I saw the provided URL, but the solution could not be found.

**Comment by sakebook** [comment]
@grantland It has not yet been resolved. Please help me.

**Comment by sakebook** [comment]
Cannot close issue.
