### ISSUE TITLE
X-Parse-Client-Key because its value was null.

### ISSUE THREAD

**Issue by ageapps** [ParsePlatform/Parse-SDK-Android#466]
I am using a Parse server with:

node version: v6.2.0
Python version: 2.7.11
Mongo version: 3.2.6
parse-server version: 2.2.10

And the App is running:

sdk version: 23
parse idk version: 1.13.0

I initialize parse in my Application.java:
`Parse.initialize(new Parse.Configuration.Builder(this).applicationId("---AppId---")
.clientKey(null)
.server("---server-url---") // i am using / at the end 
.build()
);`
An my query looks like this:
` ParseGeoPoint location = Utils.getLocation(this);

        ParseQuery<ParseObject> query = ParseQuery.getQuery("MyClass");
        query.whereNear("location", location);
        query.setLimit(100);
        query.findInBackground(new FindCallback<ParseObject>() { 
         @Override
            public void done(List<ParseObject> objects, ParseException e) {          
              if (e == null) {...... // my code}
              } else {
                    try {
                        throw new ParseException(e.getCode(), e.getMessage());
                    } catch (ParseException e1) {
                        e1.printStackTrace();
                    }
                }
            }
        });`

It is very strange because, i have an IOS app running and making the same query to the server and it works fine, but in Android i get this log:

`W/System: Ignoring header X-Parse-Client-Key because its value was null.
W/System: Ignoring header X-Parse-Client-Key because its value was null.
W/System: Ignoring header X-Parse-Client-Key because its value was null.
W/System: Ignoring header X-Parse-Client-Key because its value was null.
W/System.err: com.parse.ParseException: 
W/System.err:     at es.age.apps.myapp.activities.DispatchActivity$1.done(MyActivity.java:72)
W/System.err:     at es.age.apps.myapp.activities.DispatchActivity$1.done(MyActivity.java:61)
 W/System.err:     at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:116)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:746)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:148)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5443)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) `

If you could help me to solve this issue, help is appreciated!!! thanks

**Comment by ageapps** [comment]
Solved it, it was all my fault.
The problem was that i was passing wrong arguments in the query for the location.
