### ISSUE TITLE
ParsePush.subscribeInBackground issue

### ISSUE THREAD

**Issue by Gameleon12** [ParsePlatform/Parse-SDK-Android#477]
Currently the `ParsePush.subscribeInBackground` and `ParsePush.unsubscribeInBackground` methods seem to be broken. Whenever the application calls these methods the task returns with the following exception:

```
com.parse.ParseRequest$ParseRequestException: objects to add must be an array
at com.parse.ParseRequest.newPermanentException(ParseRequest.java:270)
at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:301)
at com.parse.ParseRequest$3.then(ParseRequest.java:137)
at com.parse.ParseRequest$3.then(ParseRequest.java:133)
at bolts.Task$15.run(Task.java:917)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeAfterTask(Task.java:908)
at bolts.Task.continueWithTask(Task.java:715)
at bolts.Task.continueWithTask(Task.java:726)
at bolts.Task$13.then(Task.java:818)
at bolts.Task$13.then(Task.java:806)
at bolts.Task$15.run(Task.java:917)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

This issue does not occur on the iOS or JavaScript SDK equivalent of these methods connected to the same server.

**Comment by Gameleon12** [comment]
Turns out it was a very specific issue in parse-server 2.2.13, only surfacing in the type of call the Android SDK uses to update it's subscriptions. It was fixed in parse-server 2.2.14.
