### ISSUE TITLE
ParseFile.save() Fails with "POST must have a request body" v1.13.1

### ISSUE THREAD

**Issue by StuStirling** [ParsePlatform/Parse-SDK-Android#558]
When updating to v1.13.1 I could no longer save files. Downgrading enabled file upload again. Here is the exception:

```
12-07 18:51:09.275 4251-4251/? E/SyncService:104: java.lang.IllegalArgumentException: method POST must have a request body.
                                                      at okhttp3.Request$Builder.method(Request.java:236)
                                                      at okhttp3.Request$Builder.post(Request.java:210)
                                                      at com.parse.ParseOkHttpClient.getRequest(ParseOkHttpClient.java:155)
                                                      at com.parse.ParseOkHttpClient.executeInternal(ParseOkHttpClient.java:64)
                                                      at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
                                                      at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
                                                      at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
                                                      at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
                                                      at com.parse.ParseRequest$3.then(ParseRequest.java:136)
                                                      at com.parse.ParseRequest$3.then(ParseRequest.java:133)
                                                      at bolts.Task$15.run(Task.java:917)
                                                      at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                                      at bolts.Task.completeAfterTask(Task.java:908)
                                                      at bolts.Task.continueWithTask(Task.java:715)
                                                      at bolts.Task.continueWithTask(Task.java:726)
                                                      at bolts.Task$13.then(Task.java:818)
                                                      at bolts.Task$13.then(Task.java:806)
                                                      at bolts.Task$15.run(Task.java:917)
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                      at java.lang.Thread.run(Thread.java:818)

```

`ParseFile` creation and upload definitely correct because I have been using it for a while and downgrading immediately resolved the issue

**Comment by rogerhu** [comment]
https://github.com/ParsePlatform/Parse-SDK-Android/pull/364
