### ISSUE TITLE
clientId cannot be null = causes invalid session tokens

### ISSUE THREAD

**Issue by chrisjenx** [ParsePlatform/Parse-SDK-Android#559]
Your documentation is incorrect you suggest the clientId should be null for opensource servers, this breaks header checking in okhttp:

This is the only config I could get to work to avoid session validation fails.
```
Parse.Configuration.Builder(application)
                    .applicationId(metaDataManager.parseAppId)
                    .clientKey("")
                    .server("https://myserver/parse/")
                    .build()
                    .apply { Parse.initialize(this) }
```

```
java.lang.NullPointerException: value == null
at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:316)
at okhttp3.Headers$Builder.add(Headers.java:270)
at com.parse.ParseOkHttpClient.getRequest(ParseOkHttpClient.java:138)
at com.parse.ParseOkHttpClient.executeInternal(ParseOkHttpClient.java:64)
at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
at com.parse.ParseRequest$3.then(ParseRequest.java:136)
at com.parse.ParseRequest$3.then(ParseRequest.java:133)
at bolts.Task$15.run(Task.java:917)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeAfterTask(Task.java:908)
at bolts.Task.continueWithTask(Task.java:715)
at bolts.Task.continueWithTask(Task.java:726)
at bolts.Task$13.then(Task.java:818)
at bolts.Task$13.then(Task.java:806)
at bolts.Task$15.run(Task.java:917)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by bleppard** [comment]
We can verify that this workaround works for us.

**Comment by mmarshak** [comment]
I have the same issue with the Android client, if I set the cliekntKey to null the app crash with the exact same trace. Please correct the docs.

**Comment by rogerhu** [comment]
https://github.com/ParsePlatform/Parse-SDK-Android/pull/506/files
