### ISSUE TITLE
back4app - i/o failure Code: 100

### ISSUE THREAD

**Issue by Joelo14** [ParsePlatform/Parse-SDK-Android#561]
I cannot fetch data just with a specific function, I have 4 functions all works properly just one got mi i/o failure, here the stack trace:

 com.parse.ParseRequest$ParseRequestException: i/o failure
     at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:290)
     at com.parse.ParseRequest$2.then(ParseRequest.java:145)
     at com.parse.ParseRequest$2.then(ParseRequest.java:139)
     at bolts.Task$15.run(Task.java:917)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
 Caused by: java.net.SocketTimeoutException: timeout
     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
     at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
     at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
     at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
     at com.parse.ParseURLConnectionHttpClient.getResponse(ParseURLConnectionHttpClient.java:106)
     at com.parse.ParseURLConnectionHttpClient.executeInternal(ParseURLConnectionHttpClient.java:57)
     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
     at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
     at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
     at com.parse.ParseRequest$3.then(ParseRequest.java:136)
     at com.parse.ParseRequest$3.then(ParseRequest.java:133)
     at bolts.Task$15.run(Task.java:917)
     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
     at bolts.Task.completeAfterTask(Task.java:908)
     at bolts.Task.continueWithTask(Task.java:715)
     at bolts.Task.continueWithTask(Task.java:726)
     at bolts.Task$13.then(Task.java:818)
     at bolts.Task$13.then(Task.java:806)

bolts-tasks-1.4.0.
Parse-1.13.0

please help to find a solution.

**Comment by mlauwers-edentify** [comment]
I have received reports that some of my users are receiving the same i/o failure message. Did you ever find a solution?

**Comment by rogerhu** [comment]
Caused by: java.net.SocketTimeoutException: timeout -> that suggests an OkHttp network timeout.  Can you add the ParseStethoInterceptor (http://guides.codepath.com/android/Configuring-a-Parse-Server#troubleshooting-parse-server) to try to see what's going on?

**Comment by Jawnnypoo** [comment]
I am sure this is just users who are offline, expecting the app to work (having no idea it needs internet access) This is a very common exception to see when a user is offline. Not really an issue with the Parse SDK itself.

**Comment by rogerhu** [comment]
So sounds like we can close then?

**Comment by Jawnnypoo** [comment]
Yes, this is a non-issue 👍
