### ISSUE TITLE
CloseGuard issues

### ISSUE THREAD

**Issue by natario1** [ParsePlatform/Parse-SDK-Android#565]
I always had these warnings but never posted about them.

When using ParseFile.getData(), 9 times out of 10 I get this error printed out:
```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                       java.lang.Throwable: Explicit termination method 'close' not called
                                                                           at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                           at java.io.FileOutputStream.<init>(FileOutputStream.java:90)
                                                                           at java.io.FileOutputStream.<init>(FileOutputStream.java:73)
                                                                           at com.parse.ParseFileUtils.openOutputStream(ParseFileUtils.java:162)
                                                                           at com.parse.ParseAWSRequest$1.call(ParseAWSRequest.java:59)
                                                                           at com.parse.ParseAWSRequest$1.call(ParseAWSRequest.java:51)
                                                                           at bolts.Task$4.run(Task.java:357)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                           at java.lang.Thread.run(Thread.java:856)
```

Should be referred to [this](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseAWSRequest.java#L59), which is never closed.

**Comment by Jawnnypoo** [comment]
@natario1 Would you be willing to make a PR closing that stream?

**Comment by natario1** [comment]
@Jawnnypoo I’m not good at this. Would adding `tempFileStream.close()` [here](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseAWSRequest.java#L75) make it? If it’s just a line, I think I can bear it :-)

**Comment by Jawnnypoo** [comment]
Yep, but I would use `ParseIOUtils.closeQuietly(tempFileStream);` to be consistent
