### ISSUE TITLE
Logging in user into Parse returns IllegalArgumentException

### ISSUE THREAD

**Issue by verygreenboi** [ParsePlatform/Parse-SDK-Android#587]
I am currently working on an Android application, and using Parse SDK as a backend service. I am running the backend on Heroku. Suddenly, whenever I tried to log the user into the server, it returns this error message

`java.lang.IllegalArgumentException: value == null`

This is the code I run to login:

```
ParseUser.logInInBackground(usernameEntry, passwordEntry, (user, e) -> {

                if (e == null){
                    mLoginView.isLogginIn(false);
                    mLoginView.onSuccess(user.getObjectId());
                } else {
                    e.printStackTrace();
                    mLoginView.onFailure(e.getMessage(), e.hashCode());
                }
            });
```

Here's my logcat

```
/xxx.xxx.bambam.debug W/System.err: com.parse.ParseException: java.lang.IllegalArgumentException: value == null
/xxx.xxx.bambam.debug W/System.err:     at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:114)
/xxx.xxx.bambam.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
/xxx.xxx.bambam.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
/xxx.xxx.bambam.debug W/System.err:     at android.os.Looper.loop(Looper.java:207)
/xxx.xxx.bambam.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5728)
/xxx.xxx.bambam.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
/xxx.xxx.bambam.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
/xxx.xxx.bambam.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
/xxx.xxx.bambam.debug W/System.err: Caused by: java.lang.IllegalArgumentException: value == null
/xxx.xxx.bambam.debug W/System.err:     at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:279)
/xxx.xxx.bambam.debug W/System.err:     at okhttp3.Headers$Builder.add(Headers.java:233)
/xxx.xxx.bambam.debug W/System.err:     at com.parse.ParseOkHttpClient.getRequest(ParseOkHttpClient.java:138)
/xxx.xxx.bambam.debug W/System.err:     at com.parse.ParseOkHttpClient.executeInternal(ParseOkHttpClient.java:64)
/xxx.xxx.bambam.debug W/System.err:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
/xxx.xxx.bambam.debug W/System.err:     at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
/xxx.xxx.bambam.debug W/System.err:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
/xxx.xxx.bambam.debug W/System.err:     at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
/xxx.xxx.bambam.debug W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:136)
/xxx.xxx.bambam.debug W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:133)
/xxx.xxx.bambam.debug W/System.err:     at bolts.Task$15.run(Task.java:917)
/xxx.xxx.bambam.debug W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
/xxx.xxx.bambam.debug W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
/xxx.xxx.bambam.debug W/System.err:     at bolts.Task.continueWithTask(Task.java:715)
/xxx.xxx.bambam.debug W/System.err:     at bolts.Task.continueWithTask(Task.java:726)
/xxx.xxx.bambam.debug W/System.err:     at bolts.Task$13.then(Task.java:818)
/xxx.xxx.bambam.debug W/System.err:     at bolts.Task$13.then(Task.java:806)
/xxx.xxx.bambam.debug W/System.err:     at bolts.Task$15.run(Task.java:917)
/xxx.xxx.bambam.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
/xxx.xxx.bambam.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
/xxx.xxx.bambam.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

These are the installed dependencies

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    wearApp project(':wear')


    compile 'com.android.support:support-v4:25.0.1'
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.android.support:palette-v7:25.0.1'
    compile 'com.android.support:cardview-v7:25.0.1'
    compile 'com.parse.bolts:bolts-android:1.4.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.jakewharton:butterknife:8.4.0'
    compile 'com.github.aliab:circular-music-progressbar:v1.0'
    compile 'com.airbnb:deeplinkdispatch:2.0.1'
    compile 'io.reactivex:rxandroid:1.0.1'
    compile 'io.reactivex:rxjava:1.0.14'
    compile 'io.reactivex:rxjava-math:1.0.0'
    compile 'com.jakewharton.rxbinding:rxbinding:0.4.0'
    compile 'io.realm:android-adapters:1.4.0'
    compile 'com.google.dagger:dagger:2.4'
    compile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta2'
    compile 'com.github.kaushikgopal:CoreTextUtils:c703fa12b6'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.github.florent37:diagonallayout:1.0.2'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.flaviofaria:kenburnsview:1.0.7'
    compile 'com.romandanylyk:pageindicatorview:0.0.7'
    compile 'com.amitshekhar.android:android-networking:0.3.0'
    compile 'com.android.support:recyclerview-v7:25.0.1'
    compile 'com.parse:parse-android:1.13.1'
    compile group: 'commons-io', name: 'commons-io', version: '2.5'
    compile 'com.infstory:rxbolts-tasks:1.0.3'
    testCompile 'junit:junit:4.12'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
    apt 'org.projectlombok:lombok:1.16.6'
    apt 'com.google.dagger:dagger-compiler:2.4'
    provided 'org.projectlombok:lombok:1.16.6'
}
```

**Comment by verygreenboi** [comment]
So, I solved this by removing okhttp from my dependencies and it now works.
