### ISSUE TITLE
Issue integrating with React Native

### ISSUE THREAD

**Issue by cinder92** [ParsePlatform/Parse-SDK-Android#609]
After integrate parse my app was working ok, for testing i just install it, then uninstalled again, parse make this issue comming out

```
:app:transformClassesWithJarMergingForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okhttp3/internal/ws/RealWebSocket$1.class
```

i have this code in build.gradle

```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    //compile 'com.parse:parse-android:1.14.0' <-- commented app works, uncommented getting above issue
}
```

Actually React Native is using okhttp 3.6 i think maybe was a duplicate somewere...

RN version : 0.42.3

**Comment by rogerhu** [comment]
Can you do ./gradlew :app:dependencies and see what OkHttp version is being added?  It may be 2 different versinos.

**Comment by cinder92** [comment]
@rogerhu  thanks for quick reply im getting this, just copied interested in part

```
|    +--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.6.0 (*)
|    +--- com.squareup.okhttp3:okhttp-urlconnection:3.4.1
|    |    \--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.6.0 (*)
|    +--- com.squareup.okhttp3:okhttp-ws:3.4.1
|    |    \--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.6.0 (*)
|    +--- com.squareup.okio:okio:1.9.0 -> 1.11.0
|    \--- org.webkit:android-jsc:r174650
+--- com.parse.bolts:bolts-android:1.+ -> 1.4.0
|    +--- com.parse.bolts:bolts-tasks:1.4.0
|    \--- com.parse.bolts:bolts-applinks:1.4.0
|         \--- com.parse.bolts:bolts-tasks:1.4.0
\--- com.parse:parse-android:1.+ -> 1.14.0
     +--- com.parse.bolts:bolts-tasks:1.4.0
     \--- com.squareup.okhttp3:okhttp:3.6.0 (*)
```

**Comment by rogerhu** [comment]
I ran a build with those two packages and don't see the exception.  Do you have any other dependent packages that are pulling OkHttp3?  Do you have a Parse.jar file somewhere for instance in your libs/ dir being used?

**Comment by cinder92** [comment]
nope, i don't have any other dependencies or Parse.jar in libs... i just have 8 hours trying to figured out this issue...

**Comment by rogerhu** [comment]
Are those the other dependencies?  Can you have the full list?

**Comment by cinder92** [comment]
sure, here they are (at this time i'm creating a new project to discard this)

```
+--- com.android.support:appcompat-v7:23.0.1
|    \--- com.android.support:support-v4:23.0.1 -> 23.4.0
|         \--- com.android.support:support-annotations:23.4.0
+--- com.facebook.react:react-native:+ -> 0.42.3
|    +--- javax.inject:javax.inject:1
|    +--- com.android.support:appcompat-v7:23.0.1 (*)
|    +--- com.android.support:recyclerview-v7:23.4.0
|    |    +--- com.android.support:support-annotations:23.4.0
|    |    \--- com.android.support:support-v4:23.4.0 (*)
|    +--- com.facebook.fbui.textlayoutbuilder:textlayoutbuilder:1.0.0
|    |    \--- com.facebook.fbui.textlayoutbuilder:staticlayout-proxy:1.0
|    +--- com.facebook.fresco:fresco:0.11.0
|    |    +--- com.facebook.fresco:drawee:0.11.0
|    |    |    +--- com.android.support:support-v4:23.2.1 -> 23.4.0 (*)
|    |    |    \--- com.facebook.fresco:fbcore:0.11.0
|    |    +--- com.facebook.fresco:fbcore:0.11.0
|    |    \--- com.facebook.fresco:imagepipeline:0.11.0
|    |         +--- com.android.support:support-v4:23.2.1 -> 23.4.0 (*)
|    |         +--- com.facebook.fresco:fbcore:0.11.0
|    |         +--- com.parse.bolts:bolts-tasks:1.4.0
|    |         +--- com.nineoldandroids:library:2.4.0
|    |         \--- com.facebook.fresco:imagepipeline-base:0.11.0
|    |              +--- com.android.support:support-v4:23.2.1 -> 23.4.0 (*)
|    |              +--- com.facebook.fresco:fbcore:0.11.0
|    |              +--- com.parse.bolts:bolts-tasks:1.4.0
|    |              \--- com.nineoldandroids:library:2.4.0
|    +--- com.facebook.fresco:imagepipeline-okhttp3:0.11.0
|    |    +--- com.facebook.fresco:fbcore:0.11.0
|    |    +--- com.squareup.okhttp3:okhttp:3.0.1 -> 3.6.0
|    |    |    \--- com.squareup.okio:okio:1.11.0
|    |    \--- com.facebook.fresco:imagepipeline:0.11.0 (*)
|    +--- com.facebook.soloader:soloader:0.1.0
|    +--- com.google.code.findbugs:jsr305:3.0.0
|    +--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.6.0 (*)
|    +--- com.squareup.okhttp3:okhttp-urlconnection:3.4.1
|    |    \--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.6.0 (*)
|    +--- com.squareup.okhttp3:okhttp-ws:3.4.1
|    |    \--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.6.0 (*)
|    +--- com.squareup.okio:okio:1.9.0 -> 1.11.0
|    \--- org.webkit:android-jsc:r174650
+--- com.parse.bolts:bolts-android:1.+ -> 1.4.0
|    +--- com.parse.bolts:bolts-tasks:1.4.0
|    \--- com.parse.bolts:bolts-applinks:1.4.0
|         \--- com.parse.bolts:bolts-tasks:1.4.0
\--- com.parse:parse-android:1.+ -> 1.14.0
     +--- com.parse.bolts:bolts-tasks:1.4.0
     \--- com.squareup.okhttp3:okhttp:3.6.0 (*)
```

**Comment by cinder92** [comment]
after create a new project with that two dependencies i receive this error in console

```
Cause: com.android.dex.DexException: Multiple dex files define Lokhttp3/internal/ws/RealWebSocket$1;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lokhttp3/internal/ws/RealWebSocket$1;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.
```

maybe i need something else? like sdk update? or something? i just updated my android studio today, with latest sdk

**Comment by rogerhu** [comment]
How are you able to get 0.42.3 for Reactive Native? 

I see:

 com.facebook.react:react-native:+ -> 0.20.1.  

You may need to do an exclude group to see if helps...

``` compile('com.example.m:m:1.0') {
     exclude group: 'org.unwanted', module: 'x 
  }
```

**Comment by cinder92** [comment]
@rogerhu  where did you see `com.facebook.react:react-native:+ -> 0.20.1`?

**Comment by rogerhu** [comment]
http://gradleplease.appspot.com/#%20com.facebook.react

Though I totally see why 0.42.3 is the latest (needs an `npm install --save github:facebook/react-native#master`?).  I'd still try to put the exclude/module statement there and see if it helps.

**Comment by cinder92** [comment]
you only need to create a project from scratch like this

`react-native init MyProject`

then in package.json you are going to see RN in 0.42.3

**Comment by cinder92** [comment]
just figured out to resolve this issue, just exclude `okhttp` from parse

```
compile('com.parse.parse-android:1.+') {
     exclude module 'okhttp'
}
```

hope helps anyone

**Comment by rogerhu** [comment]
It looks like imagepipeline tries to have its own OkHttp3 module:  com.facebook.fresco:imagepipeline-okhttp3:0.11.0
