### ISSUE TITLE
ParseObject deleteInBackground parse sdk 1.14.0 Error

### ISSUE THREAD

**Issue by ClarkXP** [ParsePlatform/Parse-SDK-Android#614]
I'm trying to call deleteInBackground on a ParseObject and I'm getting the next error:
`com.parse.ParseException: java.lang.ClassCastException: okhttp3.RequestBody$2 cannot be cast to com.parse.ParseOkHttpClient$ParseOkHttpRequestBody
                                            at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:114)
                                            at android.os.Handler.handleCallback(Handler.java:739)
                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                            at android.os.Looper.loop(Looper.java:158)
                                            at android.app.ActivityThread.main(ActivityThread.java:7229)
                                            at java.lang.reflect.Method.invoke(Native Method)
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                         Caused by: java.lang.ClassCastException: okhttp3.RequestBody$2 cannot be cast to com.parse.ParseOkHttpClient$ParseOkHttpRequestBody
                                            at com.parse.ParseOkHttpClient.getParseHttpRequest(ParseOkHttpClient.java:192)
                                            at com.parse.ParseOkHttpClient.access$000(ParseOkHttpClient.java:39)
                                            at com.parse.ParseOkHttpClient$1.intercept(ParseOkHttpClient.java:213)
                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                            at okhttp3.RealCall.execute(RealCall.java:63)
                                            at com.parse.ParseOkHttpClient.executeInternal(ParseOkHttpClient.java:67)
                                            at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:138)
                                            at com.parse.ParseDecompressInterceptor.intercept(ParseDecompressInterceptor.java:30)
                                            at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:127)
                                            at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:118)
                                            at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:127)
                                            at com.parse.ParseHttpClient.execute(ParseHttpClient.java:102)
                                            at com.parse.ParseRequest$3.then(ParseRequest.java:136)
                                            at com.parse.ParseRequest$3.then(ParseRequest.java:133)
                                            at bolts.Task$15.run(Task.java:917)
                                            at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                            at bolts.Task.completeAfterTask(Task.java:908)
                                            at bolts.Task.continueWithTask(Task.java:715)
                                            at bolts.Task.continueWithTask(Task.java:726)
                                            at bolts.Task$13.then(Task.java:818)
                                            at bolts.Task$13.then(Task.java:806)
                                            at bolts.Task$15.run(Task.java:917)
                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                            at java.lang.Thread.run(Thread.java:818)`

**Comment by rogerhu** [comment]
v1.14.1 should fix this.

**Comment by rogerhu** [comment]
Can you confirm either through a snapshot or in a few hours when v1.14.1 is released?

**Comment by ClarkXP** [comment]
it works, thank you
