### ISSUE TITLE
D/com.parse.GcmRegistrar﹕ Got error when trying to register for GCM push

### ISSUE THREAD

**Issue by danielgomezrico** [ParsePlatform/Parse-SDK-Android#69]
Initialize like this:

```
Parse.initialize(context, parseApplicationId, parseClientKey);
ParseInstallation.getCurrentInstallation().saveInBackground();
```

I´m getting the device token like this:
`String deviceToken = (String) ParseInstallation.getCurrentInstallation().get("deviceToken");`

```
D/com.parse.GcmRegistrar﹕ Got error when trying to register for GCM push
    java.lang.Exception: GCM registration error: SERVICE_NOT_AVAILABLE
            at com.parse.GcmRegistrar$Request.finish(GcmRegistrar.java:387)
            at com.parse.GcmRegistrar$Request.onReceiveResponseIntent(GcmRegistrar.java:377)
            at com.parse.GcmRegistrar.handleRegistrationIntentAsync(GcmRegistrar.java:205)
            at com.parse.GCMService.handleGcmRegistrationIntent(GCMService.java:97)
            at com.parse.GCMService.onHandleIntent(GCMService.java:83)
            at com.parse.GCMService.access$000(GCMService.java:29)
            at com.parse.GCMService$1.run(GCMService.java:63)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

What may be happening? it was working before but just and `1.10.1` didn´t fix it.

**Comment by grantland** [comment]
This sounds like an issue with GCM in Google Play Services. We currently have an exponential back off for this error here: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/GcmRegistrar.java#L370
